name: Add Recent Posts
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch:

jobs:
  update-readme-recent-blogs:
    name: Add recent posts to README.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add recent posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://hyperzsb.io/feed.xml"
          max_post_count: 3
          template: "<span>[ <a href=\"$url\" title=\"$title\">$title</a> ]</span>"