name: Add WakaTime Stats

on:
  schedule:
    # Run at 00:00 every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  update-readme-wakatime-:
    name: Add WakaTime stats to README.md
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_API_TOKEN }}
          SHOW_UPDATED_DATE: True
          UPDATED_DATE_FORMAT: "%Y/%m/%d"
          SHOW_TOTAL_CODE_TIME: True
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: True
          SHOW_OS: False
          SHOW_PROJECTS: True
          SHOW_TIMEZONE: False
          SHOW_EDITORS: True
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
